# Generated by Django 5.1 on 2024-08-21 14:52
# flake8: noqa
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(regex='^\\d+$')])),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
