# flake8: noqa
# Generated by Django 5.1 on 2024-08-14 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(regex='^\\d+$')]),
        ),
    ]
