# Generated by Django 5.1 on 2024-08-22 20:02
# flake8: noqa
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='password',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='user_name',
        ),
        migrations.AddField(
            model_name='trader',
            name='useraccount_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
