# Generated by Django 5.1 on 2024-11-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
